WITH CAR_TABLE
AS (SELECT DISTINCT CAR_ID, CAR_TYPE, DAILY_FEE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_CAR
--             CAR_RENTAL_COMPANY_RENTAL_HISTORY에는 없고 CAR_RENTAL_COMPANY_CAR에는 있는 자동차는 아무도 대여를 하지 않는 자동차 = 대여 가능한 자동차 -> outer join
            LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY
            USING(CAR_ID)
            JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            USING(CAR_TYPE)
        WHERE CAR_TYPE IN ("세단", "SUV") AND DURATION_TYPE = "30일 이상"
        GROUP BY CAR_ID
        HAVING SUM(IF(HISTORY_ID = NULL OR DATEDIFF(START_DATE, "2022-11-30") > 0 OR DATEDIFF(END_DATE, "2022-11-01") < 0, 0, 1)) = 0)

SELECT CAR_ID, CAR_TYPE, TRUNCATE(30 * DAILY_FEE * (100-DISCOUNT_RATE) * 0.01, 0) FEE
    FROM CAR_TABLE
    WHERE 30 * DAILY_FEE * (100-DISCOUNT_RATE) * 0.01 >= 500000 AND
        30 * DAILY_FEE * (100-DISCOUNT_RATE) * 0.01 < 2000000
    ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
