WITH MAX_FAVORITES
AS (SELECT FOOD_TYPE, MAX(FAVORITES) MAX_FAVORITES
        FROM REST_INFO
        GROUP BY FOOD_TYPE)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
    FROM REST_INFO JOIN MAX_FAVORITES USING (FOOD_TYPE)
    WHERE MAX_FAVORITES = FAVORITES
    ORDER BY FOOD_TYPE DESC