# SET @COUNT_2021 = (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021);

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH,
        COUNT(DISTINCT USER_ID) PUCHASED_USERS,
        ROUND(COUNT(DISTINCT USER_ID) / COUNT, 1) PUCHASED_RATIO
    FROM ONLINE_SALE
        JOIN (SELECT USER_ID, COUNT(*) OVER() COUNT
                FROM USER_INFO
                WHERE YEAR(JOINED) = 2021) U USING(USER_ID)
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
    ORDER BY YEAR, MONTH