SET @COUNT_2021 = (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021);

SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT USER_ID) PUCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID) / @COUNT_2021, 1) PUCHASED_RATIO
    FROM USER_INFO JOIN ONLINE_SALE USING(USER_ID)
    WHERE YEAR(JOINED) = 2021
    GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
    ORDER BY YEAR, MONTH