SELECT ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
    FROM ANIMAL_OUTS O JOIN ANIMAL_INS I USING(ANIMAL_ID)
    WHERE SEX_UPON_INTAKE LIKE "Intact%" AND
        (SEX_UPON_OUTCOME LIKE "Spayed%" OR SEX_UPON_OUTCOME LIKE "Neutered%")
    ORDER BY ANIMAL_ID