WITH CAR_TABLE
AS (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN "2022-08" AND "2022-10"
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5)

SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID IN (SELECT * FROM CAR_TABLE) AND DATE_FORMAT(START_DATE, "%Y-%m") BETWEEN "2022-08" AND "2022-10"
    GROUP BY MONTH(START_DATE), CAR_ID
    ORDER BY MONTH, CAR_ID DESC