WITH MAX_TABLE
AS (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
    GROUP BY CATEGORY)
    
SELECT CATEGORY, MAX_PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT JOIN MAX_TABLE USING(CATEGORY)
    WHERE PRICE = MAX_PRICE
    ORDER BY MAX_PRICE DESC