SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
    FROM REST_REVIEW
        JOIN (SELECT MEMBER_ID, MEMBER_NAME
                FROM MEMBER_PROFILE JOIN REST_REVIEW USING(MEMBER_ID)
                GROUP BY MEMBER_ID
                ORDER BY COUNT(*) DESC
                LIMIT 1) A
        USING (MEMBER_ID)
    ORDER BY REVIEW_DATE, REVIEW_TEXT