-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) TOTAL_SALES
    FROM AUTHOR JOIN (BOOK JOIN BOOK_SALES USING(BOOK_ID)) USING(AUTHOR_ID)
    WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = "2022-01"
    GROUP BY AUTHOR_ID, CATEGORY
    ORDER BY AUTHOR_ID, CATEGORY DESC