# 대여 불가능한 CAR_ID 리스트
WITH UNAVAILABILITY_TABLE
AS (SELECT CAR_ID UNAVAILABILITY
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATE("2022-10-16") BETWEEN START_DATE AND END_DATE)

SELECT DISTINCT CAR_ID, IF(CAR_ID IN (SELECT * FROM UNAVAILABILITY_TABLE), "대여중", "대여 가능") AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ORDER BY CAR_ID DESC