SELECT
DISTINCT
I2.ITEM_ID AS "ITEM_ID",
I2.ITEM_NAME AS "ITEM_NAME",
I2.RARITY AS "RARITY"
FROM ITEM_INFO I1
    JOIN ITEM_TREE T ON (I1.ITEM_ID = T.PARENT_ITEM_ID)
    JOIN ITEM_INFO I2 ON (I2.ITEM_ID = T.ITEM_ID)
WHERE I1.RARITY = "RARE"
ORDER BY I2.ITEM_ID DESC
;