SELECT ID, FN.FISH_NAME, F.LENGTH
    FROM FISH_INFO F
        JOIN FISH_NAME_INFO FN ON (F.FISH_TYPE = FN.FISH_TYPE)
        JOIN (SELECT MAX(F.LENGTH) AS "LENGTH", FN.FISH_NAME AS "FISH_NAME"
                FROM FISH_INFO F JOIN FISH_NAME_INFO FN ON (F.FISH_TYPE = FN.FISH_TYPE)
                GROUP BY FN.FISH_NAME) MF ON (MF.FISH_NAME = FN.FISH_NAME)
        WHERE MF.LENGTH = F.LENGTH
;