SELECT D.DEPT_ID AS "DEPT_ID", D.DEPT_NAME_EN AS "DEPT_NAME_EN", ROUND(AVG(SAL)) AS "AVG_SAL"
    FROM HR_EMPLOYEES E JOIN HR_DEPARTMENT D ON (E.DEPT_ID = D.DEPT_ID)
    GROUP BY D.DEPT_ID
    ORDER BY AVG_SAL DESC;